GET https://url-y.herokuapp.com/api/ HTTP/1.1

###

POST https://url-y.herokuapp.com/api/create HTTP/1.1
Content-Type: application/json

{
  "fullUrl": "https://www.google.ca/",
  "shortUrl": "ggl"
}

###

DELETE https://url-y.herokuapp.com/api/delete HTTP/1.1
Content-Type: application/json

{
  "shortUrl": "ggl"
}

###

PATCH https://url-y.herokuapp.com/api/patch HTTP/1.1
Content-Type: application/json

{
  "shortUrl": "yt",
  "newShortUrl": "ggl",
  "newFullUrl": "https://www.gglresourcescorp.com/"
}