GET http://localhost:3000/ggl HTTP/1.1

###

GET http://localhost:3000/api/get HTTP/1.1

###

POST http://localhost:3000/api/create HTTP/1.1
Content-Type: application/json

{
  "name": "YouTube",
  "fullUrl": "https://www.youtube.com/",
  "shortUrl": "yt"
}

###

DELETE http://localhost:3000/api/delete HTTP/1.1
Content-Type: application/json

{
  "shortUrl": "yt"
}

###

PATCH http://localhost:3000/api/patch HTTP/1.1
Content-Type: application/json

{
  "shortUrl": "yt",
  "newShortUrl": "ggl",
  "newFullUrl": "https://www.gglresourcescorp.com/"
}