GET http://localhost:3000/ggl HTTP/1.1

###

GET http://localhost:3000/api/get HTTP/1.1

###

POST http://localhost:3000/api/create HTTP/1.1
Content-Type: application/json

{
  "name": "YouTube",
  "actual": "https://www.youtube.com/",
  "short": "yt"
}

###

DELETE http://localhost:3000/api/delete HTTP/1.1
Content-Type: application/json

{
  "short": "ggl"
}

###

PATCH http://localhost:3000/api/patch HTTP/1.1
Content-Type: application/json

{
  "short": "yt",
  "newShort": "ggl",
  "newActual": "https://www.gglresourcescorp.com/"
}