POST http://localhost:3000/api/ HTTP/1.1
Content-Type: application/json

{
  "name": "YouTube",
  "actual": "https://www.youtube.com/",
  "short": "yt"
}

###

POST http://localhost:3000/api/ HTTP/1.1
Content-Type: application/json

{
  "name": "YouTube2",
  "actual": "123",
  "short": "yt2"
}
